<?php

namespace Repositories;

use Cache;
use Doctrine\ORM\EntityRepository;
/**
 * PhysicalInterface
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaucetController extends EntityRepository
{

    

}